name: helia_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bot_toast: ^4.1.3
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.15
  get: ^4.6.5
  intl: ^0.20.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
